server:
  port: 8082
  servlet:
    context-path: /ccraapiadmin
  tomcat:
    max-threads: 2   
spring:
  #mvc.view.prefix: /templates/
  #mvc.view.suffix: .html
  web:
    resources:
        static-locations:
            classpath: /online/src/main/resources/static/
  jpa:
    show-sql: true
    #https://stackoverflow.com/questions/65488808/difference-between-spring-jpa-properties-hibernate-and-spring-jpa-hibernate
    hibernate:
      #https://stackoverflow.com/questions/438146/what-are-the-possible-values-of-the-hibernate-hbm2ddl-auto-configuration-and-wha
      ddl-auto: none
      #https://stackoverflow.com/questions/35874587/hibernate-keeps-dropping-creating-tables-when-entitymanagerfactory-is-created      
      #'mvn clean install' always drop tables if ddl-auto = create-drop
      #ddl-auto: create-drop
      
      dialect: org.hibernate.dialect.SQLServer2012Dialect
  datasource:
    #https://techcommunity.microsoft.com/t5/azure-database-support-blog/pkix-path-building-failed-unable-to-find-valid-certification/ba-p/2591304
    url: jdbc:sqlserver://10.11.60.228:1433;databaseName=DBHK_API_TEST;TrustServerCertificate=True
#    url: jdbc:sqlserver://10.11.60.228:1433;databaseName=DBHK_PROD;TrustServerCertificate=True
    #url: jdbc:sqlserver://10.11.60.179:1433;databaseName=DBHK_PROD;TrustServerCertificate=True
    #url: jdbc:jtds:sqlserver://10.11.60.228:1433/DBHK_PROD
    #url: jdbc:jtds:sqlserver://10.11.60.179:1433/DBHK_PROD
    username: sa
    password: P@ssw0rd
    #driverClassName: net.sourceforge.jtds.jdbc.Driver
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    db:
#        ccraapi:     
#            driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#            url: jdbc:sqlserver://10.11.60.228:1433;databaseName=DBHK_API;TrustServerCertificate=True
#            username: sa
#            password: P@ssw0rd    
#        ccraportal:
#            driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#            url: jdbc:sqlserver://10.11.60.228:1433;databaseName=DBHK_PROD;TrustServerCertificate=True
#            username: sa
#            password: P@ssw0rd

jwt:
  secret: QVJTb2Z0UmVkY3Jvc3NETVM=
  key:
      pass: h%rAp^229
  expire.hour: 1
  expire.minute: 5
    

logging:
    level:
        org:
            springframework:
                jdbc:
                    core: TRACE
